In [1]:
import numpy as np
import cv2
import json

In [2]:
img_name = ["test.jpg"]

for img in img_name:
    image = cv2.imread("test.jpg")
    # print(image)
    json_name = img[:-3] + "json"
    print(json_name)
    
    with open(json_name, 'r') as f:
        json_data = json.load(f)

    label = json_data['shapes'][0]['label']
    shapes = json_data['shapes'][0]['points']

    print(f"label = {label}")
    print(f"shapes = {shapes}")

    x_min,x_max = (shapes[0][0],shapes[1][0]) if shapes[0][0] < shapes[1][0] else (shapes[1][0],shapes[0][0])
    y_min,y_max = (shapes[0][1],shapes[1][1]) if shapes[0][1] < shapes[1][1] else (shapes[1][1],shapes[0][1])
    # print(f" ")
    x_min,x_max,y_min,y_max = map(int, (x_min,x_max,y_min,y_max))

    image[:][:] = 0
    image[y_min:y_max, x_min:x_max] = 255

    roi_img = img[:-4] + "roi.jpg"
    print(roi_img)
    cv2.imwrite(roi_img, image)
    

test.json
label = slit
shapes = [[251.37106918238993, 252.45911949685532], [264.57861635220127, 269.44025157232704]]
251.37106918238993 264.57861635220127


In [3]:
# image = cv2.imread("test.jpg", cv2.IMREAD_GRAYSCALE)

# (x,y), (w,h) = (200,200), (30,50)


# print(image)


In [4]:
# cv2.rectangle(image, (x_min,y_min,x_max,y_max), 255, 1)
import numpy as np
import cv2
import json

# image = cv2.imread("test2.tif")

# print(image)
# print(image.shape)

# cv2.imshow("image", image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(512, 512, 3)


testroi.jpg


True